---

- name: Create Pyats Testbed From Ansible Inventory
  hosts: "{{ _devices }}"
  gather_facts: false
  vars:
    _devices:
      - all

  tasks:
    - name: Flatten Group Name To Device List.
      ansible.builtin.set_fact:
        _testbed: '{{ _devices | map("extract", groups) | flatten | list }}'

    - name: Template Ansible Inventory Devices To Testbed.yml
      ansible.builtin.template:
        src: ../templates/2testbed.j2
        dest: ../../testbed.yml
        mode: '0644'
      delegate_to: localhost
      tags:
        - skip_ansible_lint
